services:
  - type: web
    name: bmi_app
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DB_HOST
        value: dpg-cppa8huehbks73bueno0-a
      - key: DB_NAME
        value: data_record
      - key: DB_USER
        value: data_record_user
      - key: DB_PASS
        value: XXFgzgwnpUJLUrU6SRmXLq5w08sB0TJT
      - key: DB_PORT
        value: 5432
