services:
  - type: web
    name: bmi_app
    env: python
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: data_record  # 替换为你的数据库名称
          property: dpg-cppa8huehbks73bueno0-a #connectionString
